#!/usr/bin/env python3
"""Classify Cargo diagnostics and enforce per-example expectations.

Expectations come from manifest.json, generated by gen.py:
  compile       must compile with zero errors
  fragment      may fail only for resolution/extraction/type-inference reasons
  compile_fail  must fail to compile
  auto          legacy classifier + baseline.txt
  ignore/nightly are not generated as Cargo examples

Known failures of strict `compile` examples live separately in
good-exceptions.txt. Both migration debt files identify exact extracted blocks,
so one failure cannot accidentally bless a different block in the same section.
Stale debt entries are rejected: when a failure disappears or changes shape, the
corresponding exemption must be removed rather than silently accumulating.
"""
import collections
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
manifest = json.loads((HERE / "manifest.json").read_text())

RES_CODES = {"E0432", "E0433", "E0412", "E0425", "E0405", "E0531", "E0422",
             "E0423", "E0573", "E0463", "E0583"}
RES_PREFIXES = ("cannot find", "unresolved import", "failed to resolve",
                "use of undeclared", "cannot determine", "can't find crate",
                "maybe a missing crate", "unresolved module")
LOW_CODES = {"E0282", "E0283"}


def code_of(d):
    return (d.get("code") or {}).get("code")


def is_resolution(d):
    if code_of(d) in RES_CODES:
        return True
    return any(d.get("message", "").startswith(p) for p in RES_PREFIXES)


def is_artifact(d):
    m = d.get("message", "")
    if "parameter is only allowed in associated functions" in m:
        return True
    if code_of(d) in {"E0586", "E0585"}:
        return True
    if "`...`" in m or "missing documentation" in m:
        return True
    if "await is only allowed inside" in m:
        return True
    return False


def token(d):
    c = code_of(d)
    if c:
        return c
    words = d.get("message", "").lower().split()
    return "P:" + " ".join(words[:5])


def parse(path):
    errors = collections.defaultdict(list)
    with open(path) as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw.startswith("{"):
                continue
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if rec.get("reason") != "compiler-message":
                continue
            msg = rec.get("message", {})
            if msg.get("level") != "error":
                continue
            tgt = (rec.get("target") or {}).get("name")
            if tgt:
                errors[tgt].append(msg)
    return errors


def diagnostic_tokens(diags):
    return ",".join(sorted({token(d) for d in diags})) or "COMPILED"


def block_ordinal(ex):
    try:
        return int(ex.rsplit("__", 1)[1]) + 1
    except (IndexError, ValueError):
        return "?"


def legacy_signature(ex, diags):
    """Exact migration signature for one legacy `auto` block."""
    info = manifest.get(ex, {})
    return (
        f"{info.get('file', '?')} :: {info.get('section', '?')} :: "
        f"block {block_ordinal(ex)} :: {diagnostic_tokens(diags)}"
    )


def strict_signature(ex, diags):
    """Identify one exact extracted strict block and its diagnostic shape."""
    info = manifest.get(ex, {})
    return (
        f"{info.get('file', '?')} :: {info.get('section', '?')} :: "
        f"block {block_ordinal(ex)} :: {diagnostic_tokens(diags)}"
    )


def legacy_classify(diags):
    nonres = [d for d in diags if not is_resolution(d)]
    if not nonres:
        return "fragment", []
    if all(is_artifact(d) for d in nonres):
        return "artifact", []
    real = [d for d in nonres if not is_artifact(d)]
    if real and all(code_of(d) in LOW_CODES for d in real):
        return "low", []
    suspects = [d for d in real if code_of(d) not in LOW_CODES]
    return "suspect", suspects


def fragment_ok(diags):
    if not diags:
        return True
    kind, _ = legacy_classify(diags)
    return kind in {"fragment", "artifact", "low"}


def reason_for_compile_failure(diags):
    if diags and all(is_resolution(d) for d in diags):
        return "standalone fragment: unresolved context"
    nonres = [d for d in diags if not is_resolution(d)]
    if nonres and all(is_artifact(d) for d in nonres):
        return "extraction artifact: wrapper/context"
    real = [d for d in nonres if not is_artifact(d)]
    if real and all(code_of(d) in LOW_CODES for d in real):
        return "standalone fragment: type inference needs surrounding context"
    return "legacy compile failure: repair example or add explicit rust-check metadata"


def load_baseline(path):
    return {l.strip() for l in open(path) if l.strip() and not l.startswith("#")}


def load_good_exceptions(path):
    out = {}
    p = pathlib.Path(path)
    if not p.exists():
        return out
    for raw in p.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if " || " not in line:
            raise SystemExit(f"bad good-exceptions line (missing ' || '): {line}")
        sig, reason = line.split(" || ", 1)
        if not reason.strip():
            raise SystemExit(f"good-exceptions entry has no reason: {sig}")
        if " :: block " not in sig:
            raise SystemExit(f"good-exceptions entry does not identify an exact block: {sig}")
        out[sig.strip()] = reason.strip()
    return out


def collect(errors):
    auto_suspects = {}
    violations = {}
    stats = collections.Counter()
    for ex, info in manifest.items():
        if not info.get("generated", True):
            stats[info.get("expect", "ignored")] += 1
            continue
        diags = errors.get(ex, [])
        expect = info.get("expect", "auto")
        stats[expect] += 1
        if expect == "compile":
            if diags:
                violations[ex] = ("expected compile", diags)
        elif expect == "fragment":
            if not fragment_ok(diags):
                violations[ex] = ("fragment has non-fragment errors", diags)
        elif expect == "compile_fail":
            if not diags:
                violations[ex] = ("expected compile failure, but compiled", [])
        elif expect == "auto":
            kind, suspect = legacy_classify(diags)
            stats[f"auto:{kind}"] += 1
            if kind == "suspect":
                auto_suspects[ex] = suspect
        else:
            raise SystemExit(f"unknown generated expectation {expect!r} for {ex}")
    return auto_suspects, violations, stats


def main():
    args = sys.argv[1:]
    path = next((a for a in args if not a.startswith("--")), "check.json")
    errors = parse(path)
    auto_suspects, violations, stats = collect(errors)
    auto_sigs = sorted({legacy_signature(ex, d) for ex, d in auto_suspects.items()})
    violation_sigs = {
        strict_signature(ex, d): (ex, why, d)
        for ex, (why, d) in violations.items()
    }

    if "--emit-baseline" in args:
        print("\n".join(auto_sigs))
        return

    if "--emit-good-exceptions" in args:
        rows = []
        for sig, (_ex, _why, diags) in violation_sigs.items():
            rows.append(f"{sig} || {reason_for_compile_failure(diags)}")
        print("\n".join(sorted(rows)))
        return

    if "--check-baseline" in args:
        bpath = args[args.index("--check-baseline") + 1]
        gpath = args[args.index("--good-exceptions") + 1] if "--good-exceptions" in args else str(HERE / "good-exceptions.txt")
        base = load_baseline(bpath)
        allowed = load_good_exceptions(gpath)

        current_auto = set(auto_sigs)
        new_auto = sorted(current_auto - base)
        stale_auto = sorted(base - current_auto)
        current_violation_sigs = set(violation_sigs)
        new_good = sorted(current_violation_sigs - set(allowed))
        stale_good = sorted(set(allowed) - current_violation_sigs)

        failed = False
        if new_good:
            failed = True
            print(f"FAIL: {len(new_good)} recommended/explicit expectation violation(s):\n")
            for s in new_good:
                print(f"  + {s}")
            print("\nFix the example or add explicit `rust-check` metadata. During migration only, "
                  "an exact debt entry with a reason may be added to good-exceptions.txt.\n")
        if stale_good:
            failed = True
            print(f"FAIL: {len(stale_good)} stale good-exception(s); remove them because the exact failure is gone:\n")
            for s in stale_good:
                print(f"  - {s}")
            print()
        if new_auto:
            failed = True
            print(f"FAIL: {len(new_auto)} new legacy compile-suspect(s) not in baseline:\n")
            print("\n".join(f"  + {s}" for s in new_auto))
            print()
        if stale_auto:
            failed = True
            print(f"FAIL: {len(stale_auto)} stale legacy baseline entrie(s); remove them because the exact failure is gone:\n")
            print("\n".join(f"  - {s}" for s in stale_auto))
            print()
        if failed:
            sys.exit(1)

        print(
            f"OK: expectations satisfied ({len(allowed)} exact recommended-example debt entries); "
            f"legacy baseline exact and current ({len(auto_sigs)} signatures)"
        )
        return

    generated = sum(1 for x in manifest.values() if x.get("generated", True))
    failed_examples = len(errors)
    print("== compile-check summary ==")
    print(f"examples generated        : {generated}")
    print(f"compiled clean            : {generated - failed_examples}")
    print(f"expectation violations    : {len(violations)}")
    print(f"legacy auto suspects      : {len(auto_suspects)}")
    print("expectation counts        : " + ", ".join(f"{k}={v}" for k, v in sorted(stats.items()) if ":" not in k))
    for ex, (why, diags) in sorted(violations.items(), key=lambda kv: (manifest[kv[0]]["file"], manifest[kv[0]]["line"])):
        info = manifest[ex]
        print(f"\n--- {info['file']}:{info['line']} [{info['section']}] — {why}")
        if not diags:
            print("    compiled successfully")
        else:
            seen = set()
            for d in diags:
                row = (code_of(d) or "----", d.get("message", "").splitlines()[0])
                if row not in seen:
                    seen.add(row)
                    print(f"    {row[0]}: {row[1]}")


if __name__ == "__main__":
    main()
